---
$:
  npm:
    dependencies:
      chai: 'latest'

  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i

  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~

  coverage:
    reporters:
      text-summary: ~
    pattern:
      - /.+\.js$/i
    ignore:
      - /.+\.spec\.js$/i
      - /.+\.e2e\.js$/i
      - /^(.*\/)?node_modules(\/?$)?/i

  codeclimate:
    token: 'process.env.CODECLIMATE_REPO_TOKEN'

  preprocess:
    '$.codeclimate.token': 'eval'

### Add other modules here...
todomvc:
  root: 'src/deep-todomvc'