---
$:
  npm:
    dependencies:
      chai: 'latest'

  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i

  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~

### Add other modules here...
todomvc:
  root: 'src/deep-todomvc'