---
$:
  npm:
    dependencies:
      chai: 'latest'

  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i

  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~

  coverage:
    reporters:
      text-summary: ~
    pattern:
      - /.+\.js$/i
    ignore:
      - /.+\.spec\.js$/i
      - /.+\.e2e\.js$/i
      - /^(.*\/)?node_modules(\/?$)?/i

  codeclimate:
    token: '25a4c7d82bc3aefec025f0324e25b8250878078f803016c67c779ae297f7a19c'

### Add other modules here...
todomvc:
  root: 'src/deep-todomvc'