---
$:
  npm:
    dependencies:
      chai: 'latest'

  emit:
    pattern:
      - /.+\.js$/i
    ignore:
      - /^(.*\/)?node_modules(\/?$)?/i

  test:
    mocha:
      options:
        ui: 'bdd'
        reporter: 'spec'
    pattern:
      - /.+\.spec\.js$/i
    ignore: ~

  coverage:
    reporters:
      text-summary: ~
    pattern:
      - /.+\.js$/i
    ignore:
      - /.+\.spec\.js$/i
      - /.+\.e2e\.js$/i
      - /^(.*\/)?node_modules(\/?$)?/i
    compare:
      negative-delta: 3
      storage:
        driver: 's3'
        options:
          - 's3://travis-metadata/coverage/MitocGroup/tutorial-ci-for-serverless/'
          -
            region: 'process.env.AWS_DEFAULT_REGION'
            accessKeyId: 'process.env.AWS_ACCESS_KEY_ID'
            secretAccessKey: 'process.env.AWS_SECRET_ACCESS_KEY'

  codeclimate:
    token: 'process.env.CODECLIMATE_REPO_TOKEN'

  preprocess:
    '$.codeclimate.token': 'eval'
    '$.coverage.compare.storage.options.1.region': 'eval'
    '$.coverage.compare.storage.options.1.accessKeyId': 'eval'
    '$.coverage.compare.storage.options.1.secretAccessKey': 'eval'

### Add other modules here...
todomvc:
  root: 'src/deep-todomvc'